version: '3'
services:
  db:
    image: mongo:latest

  api:
    build:
      context: .
      args:
        NODE_ENV: production
    image: mern-crud

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - DB=mongodb://db/mern-crud
      - CORS=1
      - DEBUG=express:*
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: node server.js

  web:
    # build: /usr/src/app/react
    image: mern-crud
    volumes:
      - ./react-src:/usr/src/app/react
      - /usr/src/app/react/node_modules
    ports:
      - "4200:4200"
    environment:
      - "REACT_APP_API_URL=http://localhost:3000"
    depends_on:
      - api
    command: npm start --prefix react
